# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=b'')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Category')),
            ],
        ),
    ]
